version: "3"

# Define services
services:
  # App Service
  go_stripe_boekhouden_api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/go-stripe-eboekhouden
    command: dlv exec --listen=:2345 --headless --api-version=2 --log ./cmd/api
    ports:
      - 20100:8080
    depends_on:
      - go_stripe_boekhouden_db # This service depends on db. Start that first.

  # DB Service
  go_stripe_boekhouden_db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - gostripeeboekhoudendbdata:/var/lib/mysql

networks:
  default:
    external:
      name: go-stripe-eboekhouden-net
volumes:
  gostripeeboekhoudendbdata:
